### ISSUE TITLE
Add more GitHub Sponsor options

### ISSUE THREAD

**Issue by jgod** [bouiboui/facebook-saved#12]
This plugin was quite valuable to me, so I'd like to show my appreciation and encourage further development.
I'd like to give you more money than your tier list has available ($1).
Please add a custom one time payment option, and a couple different monthly payment tiers.

**Comment by bouiboui** [comment]
Wow, I didn't expect this 😄 

You're my first sponsor actually, thanks a lot! I'm very grateful.
I've enabled both custom payment options, would you be interested in any of these rewards?

<img width="793" alt="image" src="https://user-images.githubusercontent.com/3274103/157626459-84574e05-22fb-44d0-8b56-0535ba6c3ade.png">
 

Here's your promised emoji: 🤸‍♂️
Again thanks a lot! I'm very happy that this project is useful to you.

**Comment by jgod** [comment]
Yes it's great. I've used it to gather over 5k links that would otherwise force me to write my own thing. Sent a one time and bumped up the monthly a bit. - Thanks
