### ISSUE TITLE
Include Comments...

### ISSUE THREAD

**Issue by Yolakalemowa** [bouiboui/facebook-saved#8]
Hello,

Thanks for the great great great and life-saving program. I'm new to this site I have no idea if this is the right place to suggest: do you think it's possible to include the comments under the exported posts? 

When I copy as text file, it's brilliant, I can paste it and get the actual post in a word file. But the comments are as valuable to me and was always wondering if this is possible...

Thanks,
Y

**Comment by bouiboui** [comment]
This is the right place, thank you for your suggestion!

I'm afraid it's a bit too advanced for this extension, it would require to actually follow/open the links, and capture the contents of the page, it might also generate very big files since some users have thousands of saved links.

Can you share your full use case? Maybe there's a workaround.

**Comment by Yolakalemowa** [comment]
Thanks for replying,

May I ask what do you mean by share my case?

Which case?

Y

**Comment by bouiboui** [comment]
Sorry, this is a technical term. To help me understand your actual needs, I would like to know what your full process is, my understanding is that you save the posts in Word files, what do you do then, print them, store them online or locally, send them to someone? Maybe there's an extension that can use the list of links exported with this extension and do what you want with it.

**Comment by Yolakalemowa** [comment]
Oh! Pardon me.

lol I literally just tried it to show you an example, but for some reason
can't get the extension to work XD... I'm probably doing smthn wrong.

Anyway,

For now I'm just doing this for archiving. I follow a lot of academics and
they’re usually having very valuable posts and discussions in the comments
among each other. I go back all the time to these posts and comments for
reference. It’s very helpful for me to be able to “ *CTRL+F*” the entire
archive and find specific terms or names etc.

Of course it’s possible to use facebook itself to search my saved items,
but often many of these posts get removed, which is where your program
comes to the rescue. For the first time I was able to have all in text
format in a word document which is very good... (but of course no comments,
so I'm probably gonna dedicate an hour each day to archive them manually.)

thanks a lot again!

Great job :D will be following and spreading word about your project...
Maybe one day this comments issue could be solved.

cheers

**Comment by bouiboui** [comment]
That's an interesting use case, but a hard one. I was thinking about PDF files, but you wouldn't be able to search the whole archive.
This extension: https://websatchel.com/ seems to do what you want and has great reviews! Can you give it a try?

**Comment by Yolakalemowa** [comment]
Hey Julien,

Thanks for replying... That looks just like pocket is it not?

I guess with pocket you can download the entire archive (but only the links
and their names) but here you can actually download a pdf of all the
webpages? Heck, it might even work for facebook posts and their comments?

I'll check it thanks,

**Comment by bouiboui** [comment]
Pocket is great, but when the original link is gone, it's over.
I don't think it's based on PDF, it creates a searchable archive of your links, I guess you have to try it by yourself 😉

**Comment by bouiboui** [comment]
Is it ok for you if I close this issue?

**Comment by Yolakalemowa** [comment]
Oh of course you can. Go ahead, and thanks for your prompt and friendly
responses...

Keep up the good work!

(how can I contact you outside the "issues" thing?)

**Comment by bouiboui** [comment]
@Yolakalemowa You can DM me on Twitter: https://twitter.com/j_____________n
